### PR TITLE
IBM Legal required to charge the icon

### PR DESCRIPTION
**Pull request by ancatri**
IBM Legal required to charge the icon from the one potentially used in IBM We need to update the logo

### CODE REVIEW

**Comment by ancatri** [comment]
Need the new logo file to update the logo on Readme

**Review by vikas-agarwal76 — APPROVED** [review]
LGTM

**Comment by vikas-agarwal76** [comment]
@ancatri We should also delete the existing icon files in assets.

**Comment by degenaro** [comment]
Closing in favor of #72.

**Pull request closed without merging**
