### PR TITLE
Additional artwork, from Anca, from Mike Abbink

### PR DESCRIPTION
**Pull request by degenaro**
Additional artwork, from Anca, from Mike Abbink

### CODE REVIEW

**Comment by jpower432** [comment]
@degenaro Still working through a process to collect votes, exploring #71. Given this is a PR approvals could work. I added a vote label and Oversight Committee to provide approval on the new artwork.

**Comment by degenaro** [comment]
Note: artwork is toward fulfilling the needs of https://github.com/cncf/toc/issues/1371 for checking boxes `Submit a pull request with your artwork` and `Submit a pull request to add your project as a Sandbox project to the Cloud Native Landscape...`.

**Review by jflowers — APPROVED** [review]

**Review by jpower432 — CHANGES_REQUESTED** [review]
I would suggest we have consistency in font and whether we use lowercase or uppercase in the logo

**Review by ancatri — APPROVED** [review]

**Comment by vikas-agarwal76** [comment]
@degenaro @ancatri We currently have 4 images 2 with text and 2 without text. I suggest we only have 2 images without text (text can be added as required in the document where this is getting included). One image with white background and another with transparent background (for including in places where dark background is used). We have the image without text with white background. We need another image with transparent background without text.

**Review by yuji-watanabe-jp — APPROVED** [review]

**Comment by ancatri** [comment]
I prefer to minimize the work on the design team who provided the latest during their vacation .... 

@jpower432 Jenn, where do we have different fonts and case?
@vikas-agarwal76 can we crop what we need without text from what we have already?

**Comment by ancatri** [comment]
@vikas-agarwal76 we need these 18 images ... we are required what text/color to use, it's not our choice ... 
https://github.com/cncf/artwork/blob/main/examples/incubating.md
Mike provided the minimum we can work with to generate the remaining needed

**Comment by degenaro** [comment]
A few more images have been provided. I will post them to this PR shortly...

**Review by vikas-agarwal76 — APPROVED** [review]
LGTM

**Review by jpower432 — APPROVED** [review]
LGTM

**Comment by degenaro** [comment]
7 of 8 reviewers have approved. Majority vote has been achieved. Merging.

**Comment by ancatri** [comment]
@jpower432 @degenaro @vikas-agarwal76 
I explained to Mike the abbreviations and he agreed with Jenn's comment. Thanks @jpower432 for pointing this out!! 
So we have the one case version from Mike, in vacation w his family, the 8th version of these ... If this in not dedication I do not know what it is ... And this has no link to his day job whatsoever ... SO thanks @jpower432 for persevering to get what it's the best and @degenaro for reuploading for the 8th time ....

[OSCAL-compass-logos.zip](https://github.com/user-attachments/files/16802936/OSCAL-compass-logos.zip)

**Pull request merged**
