### PR TITLE
docs: adds Oversight Committee Chairs to GOVERNANCE.md

### LINKED ISSUE #36: Add Oversight Committee co-chair information and responsibilities to Governance document
Spawned from #31 

The `GOVERNANCE.md` document needs clearer responsibilities around Oversight Committee chair role and additional information about co-chairs

### PR DESCRIPTION
**Pull request by jpower432**
Closed #36 

This must be approved as part of #31

### CODE REVIEW

**Review by jflowers — APPROVED** [review]
LGTM, good clarity

**Comment by ancatri** [comment]
@jpower432 @jflowers @vikas-agarwal76 Per https://github.com/cncf/tag-security/blob/main/governance/roles.md#role-of-members the chairs have equal positions and roles. In the same vein, I suggest we keep this format for 2 chairs rather than introducing main/vice. Thanks!

**Comment by jpower432** [comment]
@ancatri I am in favor and can make this change. @jflowers @mrgadgil  Do you agree with this change?

**Comment by jflowers** [comment]
sure :-)

**Comment by mrgadgil** [comment]
LGTM. Thank you for making the change.

**Comment by jpower432** [comment]
@vikas-agarwal76 Looks like we have 2/3 committee approval on this change. Can you please take another look at the recent changes before I merge?

**Review by vikas-agarwal76 — APPROVED** [review]
LGTM

**Pull request merged**
