### PR TITLE
docs: creates an initial SECURITY.md policy

### LINKED ISSUE #4: Add an org security policy
Include:

- A org level guide for how report security vulnerabilities 
- Report to maintainer and give overall guidance

### PR DESCRIPTION
**Pull request by jpower432**
# What

This creates an initial security policy and process in the `SECUIRTY.md` .

Closes #4 

# Impacts

- Actions by admins following this merge - follow these steps for each [project](https://docs.github.com/en/code-security/security-advisories/working-with-repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository)

### CODE REVIEW

**Review by jflowers — APPROVED** [review]
LGTM

**Review by jflowers — APPROVED** [review]
Good catch

**Comment by yuji-watanabe-jp** [comment]
LGTM
+1

**Review by vikas-agarwal76 — APPROVED** [review]
LGTM

**Review by degenaro — APPROVED** [review]
LGTM

**Comment by jpower432** [comment]
Merging this with 2/3 of the reviewer approval.

**Pull request merged**
