### PR TITLE
docs: adds principles to the governance document

### LINKED ISSUE #78: Add guiding principles to the documentation

### PR DESCRIPTION
**Pull request by jpower432**
Closes #78

### CODE REVIEW

**Review by jflowers — APPROVED** [review]
LGTM

**Review by vikas-agarwal76 — APPROVED** [review]
LGTM

**Review by yuji-watanabe-jp — APPROVED** [review]

**Comment by yuji-watanabe-jp** [comment]
LGTM

**Review by degenaro — APPROVED** [review]
LGTM

**Review by ancatri — APPROVED** [review]

**Comment by jpower432** [comment]
Merging with over 2/3 reviewer approval

**Pull request merged**
