### PR TITLE
docs: updates MAINTAINERS.md with Oversight Committee chairs

### LINKED ISSUE #34: Nominate Oversight Committee chairs
## Overview

The primary role of the Oversight Committee chairs is to facilitate operations and governance of the Oversight Committee.

Chairs responsibilities include:

- Setting the agenda for meetings
- Scheduling and facilitating Oversight Committee meetings
- Extending discussion via asynchronous communication to be inclusive of members who cannot attend a specific meeting time
- Facilitating the creation and execution of Oversight Committee activities

## Eligibility 
Those who are eligible to be nominated are current Oversight Committee members listed [here](https://github.com/oscal-compass/community/blob/main/MAINTAINERS.md#oversight-committee).

## Nominations

Nominations will be open until July 5th. 

Eligible people can nominate themselves.
If you plan to nominate somebody else please ensure that they accept the nomination.

### How to nominate

Please include a short nomination **comment on this issue** with the following details:

- Name of the nominee
- Motivation for the role
- Commitment on how much time you/they can dedicate to the role

### Notes

This issue is preceding a formally defined Oversight Committee selection process. Per the governance documentation, this will be defined and finalized by the bootstrap Oversight Committee.

Based on community feedback, this can serve as a example or template for the formally defined process.

Related to #31

### PR DESCRIPTION
**Pull request by jpower432**
Closes #34

### CODE REVIEW

**Review by jflowers — APPROVED** [review]
LGTM

**Review by mrgadgil — APPROVED** [review]
Thank you. LGTM

**Comment by yuji-watanabe-jp** [comment]
LGTM

**Comment by jpower432** [comment]
Thanks @jflowers @mrgadgil @yuji-watanabe-jp for your reviews. @vikas-agarwal76 Can you please take a look? I can modify the GitHub roles following this merge.

**Review by vikas-agarwal76 — APPROVED** [review]
LGTM

**Pull request merged**
